import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { VILLAGE_LAYOUT } from '../src/data/villageLayout.js';
import { FARM_LAYOUT } from '../src/data/farmLayout.js';
import { FOREST_RUINS_LAYOUT } from '../src/data/forestRuinsLayout.js';
import { validateVillageLayout } from '../src/services/SceneValidationService.js';
import { validatePlacementRules } from '../src/services/PlacementValidationService.js';
import { validateFarmLayout } from '../src/services/FarmSceneValidationService.js';
import { validateForestRuinsLayout } from '../src/services/ForestSceneValidationService.js';
import { validateAllInteriors } from '../src/services/InteriorValidationService.js';
import { validateSkillGraph } from '../src/services/SkillGraphValidationService.js';
import { validateTrialTower } from '../src/services/TrialTowerValidationService.js';
import { validateFarmProgression } from '../src/services/FarmProgressionValidationService.js';
import { REGION_STRUCTURE_CATALOG } from '../src/data/physicalObjectCatalog.js';
import { validateAllRegionProductionLayouts } from '../src/services/RegionProductionValidationService.js';
import { validateCharacterPhysicalProfiles } from '../src/services/CharacterPhysicalValidationService.js';
import { validateProductionRuntimeContracts } from '../src/services/ProductionRuntimeValidationService.js';
import { validateRegionGameplayProduction } from '../src/services/RegionGameplayValidationService.js';
import { validateRelease022Content } from '../src/services/Release022ValidationService.js';
import { validateTerrainTraversalFoundation } from '../src/services/TerrainTraversalValidationService.js';
import { validateEnvironmentLifeContent } from '../src/services/EnvironmentLifeValidationService.js';
import { validateLifeSimulationCore } from '../src/services/LifeSimulationCoreValidationService.js';
import { validateVillageCompanionContent } from '../src/services/VillageCompanionValidationService.js';
import { validateAssetGovernanceContracts } from '../src/services/AssetGovernanceValidationService.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const packageLock = JSON.parse(fs.readFileSync(path.join(root, 'package-lock.json'), 'utf8'));
const requiredFiles = [
  'src/components/Environment/SurfaceDetailLayer.jsx',
  'src/data/indoorZones.js',
  'src/systems/npcSchedule.js',
  'src/services/InteriorValidationService.js',
  'src/data/interiorDefinitions.js',
  'src/utils/placementGeometry.js',
  'src/components/UI/CharacterCreationPanel.jsx',
  'src/components/UI/DefeatPanel.jsx',
  'src/hooks/useGamepad.js',
  'src/qa/QaBridge.jsx',
  'src/data/skillGraph.js',
  'src/services/SkillGraphValidationService.js',
  'src/services/TrialTowerValidationService.js',
  'src/services/FarmProgressionValidationService.js',
  'src/data/farmProgression.js',
  'src/systems/farmSimulation.js',
  'src/components/UI/HomeInteriorPanel.jsx',
  'src/components/Environment/SkyWeatherLayer.jsx',
  'src/components/World/RegionProductionKit.jsx',
  'src/data/regionProductionLayouts.js',
  'src/data/physicalObjectCatalog.js',
  'src/services/RegionProductionValidationService.js',
  'src/components/3D/CharacterActorRig.jsx',
  'src/data/characterPhysicalProfiles.js',
  'src/services/CharacterPhysicalValidationService.js',
  'src/components/3D/AnimatedProductionModel.jsx',
  'src/components/3D/RuntimeAcceptanceProbe.jsx',
  'src/components/Entities/RegionEncounterLayer.jsx',
  'src/data/regionEncounters.js',
  'src/data/productionAssetCatalog.js',
  'src/input/runtimeAcceptance.js',
  'src/services/ProductionRuntimeValidationService.js',
  'src/data/regionGameplayProfiles.js',
  'src/data/regionMechanicChallenges.js',
  'src/data/dailyRift.js',
  'src/components/RegionMechanics/RegionMechanicChallengePanel.jsx',
  'src/components/RegionMechanics/WindAngleChallenge.jsx',
  'src/components/RegionMechanics/SnowTemperatureChallenge.jsx',
  'src/components/RegionMechanics/FarmArrayChallenge.jsx',
  'src/components/RegionMechanics/StarPatternChallenge.jsx',
  'src/components/RegionMechanics/CrystalSymmetryChallenge.jsx',
  'src/components/RegionMechanics/CanyonMeasurementChallenge.jsx',
  'src/components/RegionMechanics/MushroomRhythmChallenge.jsx',
  'src/components/RegionMechanics/ClockworkSequenceChallenge.jsx',
  'src/services/RegionGameplayService.js',
  'src/services/RegionGameplayValidationService.js',
  'src/systems/regionLoot.js',
  'src/components/World/RegionGameplayLayer.jsx',
  'src/components/World/RegionSubareaTracker.jsx',
  'src/components/World/RegionMechanicLayer.jsx',
  'src/components/World/RegionGuideNPC.jsx',
  'src/components/World/RegionStructureInteractionLayer.jsx',
  'src/components/UI/RegionWorkshopPanel.jsx',
  'src/components/UI/DailyRiftHUD.jsx',
  'src/data/combatEncounterProfiles.js',
  'src/data/trialTowerRooms.js',
  'src/data/uiSystem.js',
  'src/data/storyContent.js',
  'src/data/npcStoryProfiles.js',
  'src/i18n/zhTW.js',
  'src/services/Release022ValidationService.js',
  'src/services/StoryProgressService.js',
  'src/services/CombatGeometryService.js',
  'src/components/Combat/BossSkillTelegraph.jsx',
  'src/components/Combat/BossPhaseBanner.jsx',
  'src/components/Trial/TrialTowerArena.jsx',
  'src/components/Trial/TrialRoomMechanic.jsx',
  'src/components/UI/HUDLayoutManager.jsx',
  'src/components/UI/AccessibilitySettingsPanel.jsx',
  'src/components/UI/VoiceGuidanceController.jsx',
  'src/components/Story/NPCDialoguePanel.jsx',
  'src/components/Story/StoryJournalSection.jsx',
  'scripts/export-release-022-manifest.mjs',
  'scripts/export-release-022-evidence.mjs',
  'public/manifests/release-content-manifest.json',
  'docs/RELEASE_022_VALIDATION.json',
  'docs/COMBAT_BOSS_ELITE_MATRIX.csv',
  'docs/TRIAL_TOWER_100_FLOOR_MATRIX.csv',
  'docs/STORY_QUEST_MATRIX.csv',
  'docs/UI_ACCESSIBILITY_MATRIX.csv',
  'docs/RELEASE_NOTES_0.22.0.md',
  'docs/REMAINING_SCOPE_0.22.0.md',
  'docs/DESTRUCTIVE_QA_0.22.0.md',
  'docs/RUNTIME_QA_STATUS_V022.md',
  'docs/BASELINE_LOCK_V022.json',
  'docs/FILE_DIFF_V019_TO_V022.txt',
  'docs/FILE_DIFF_V019_TO_V022.json',
  'docs/BUILD_20260714_V022.txt',
  'docs/SIMULATION_20260714_V022.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V022.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V022.json',
  'docs/REGION_GAMEPLAY_TEST_20260714_V022.json',
  'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V022.json',
  'docs/STATIC_AUDIT_20260714_V022.json',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V022.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V022.json',
  'docs/RUNTIME_HTTP_20260714_V022.txt',
  'docs/FILE_INVENTORY_V022_SHA256.txt',
  'scripts/run-release-022-tests.mjs',
  'scripts/run-region-gameplay-tests.mjs',
  'scripts/export-region-gameplay-manifest.mjs',
  'public/manifests/region-gameplay-manifest.json',
  'docs/REGION_GAMEPLAY_VALIDATION.json',
  'docs/REGION_GAMEPLAY_MATRIX.csv',
  'docs/RELEASE_NOTES_0.19.0.md',
  'docs/REMAINING_SCOPE_0.19.0.md',
  'docs/BASELINE_LOCK_V019.json',
  'docs/FILE_DIFF_V018_TO_V019.txt',
  'docs/FILE_DIFF_V018_TO_V019.json',
  'docs/BUILD_20260714_V019.txt',
  'docs/SIMULATION_20260714_V019.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V019.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V019.json',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V019.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V019.json',
  'docs/RUNTIME_HTTP_20260714_V019.txt',
  'docs/RUNTIME_QA_STATUS_V019.md',
  'docs/FILE_INVENTORY_V019_SHA256.txt',
  'scripts/generate-production-assets.mjs',
  'scripts/run-production-runtime-tests.mjs',
  'scripts/export-runtime-production-manifest.mjs',
  'scripts/runtime-qa-cdp.mjs',
  'public/manifests/runtime-production-manifest.json',
  'docs/PRODUCTION_RUNTIME_VALIDATION.json',
  'docs/REGION_ENCOUNTER_MATRIX.csv',
  'docs/RELEASE_NOTES_0.18.0.md',
  'docs/RUNTIME_PRODUCTION_QA_BLOCKED.md',
  'docs/BASELINE_LOCK_V018.json',
  'docs/FILE_DIFF_V017_TO_V018.txt',
  'docs/FILE_DIFF_V017_TO_V018.json',
  'docs/runtime-production-qa/runtime-report.json',
  'scripts/run-region-production-tests.mjs',
  'scripts/export-production-manifests.mjs',
  'public/manifests/region-production-manifest.json',
  'public/manifests/character-production-manifest.json',
  'docs/REGION_PRODUCTION_MATRIX.csv',
  'docs/CHARACTER_PHYSICAL_MATRIX.csv',
  'scripts/run-simulation-tests.mjs',
  'scripts/runtime-qa.mjs',
  'docs/CHANGESET_20260714_P1P5.md',
  'docs/RUNTIME_20260714_BLOCKED.md',
  'docs/REMAINING_SCOPE_20260714.md',
  'docs/BASELINE_LOCK.json',
  'docs/WORK_LEDGER.csv',
  'src/services/TraversalSurfaceService.js',
  'src/services/TerrainTraversalValidationService.js',
  'src/components/World/RegionTraversalLayer.jsx',
  'scripts/run-terrain-traversal-tests.mjs',
  'scripts/export-terrain-traversal-evidence.mjs',
  'public/manifests/terrain-traversal-manifest.json',
  'docs/TERRAIN_TRAVERSAL_VALIDATION.json',
  'docs/TERRAIN_TRAVERSAL_MATRIX.csv',
  'docs/RELEASE_NOTES_0.23.0.md',
  'docs/REMAINING_SCOPE_0.23.0.md',
  'docs/DESTRUCTIVE_QA_0.23.0.md',
  'docs/RUNTIME_QA_STATUS_V023.md',
  'docs/BASELINE_LOCK_V023.json',
  'docs/FILE_DIFF_V022_TO_V023.txt',
  'docs/FILE_DIFF_V022_TO_V023.json',
  'docs/BUILD_20260714_V023.txt',
  'docs/TERRAIN_TRAVERSAL_TEST_20260714_V023.json',
  'docs/SIMULATION_20260714_V023.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V023.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V023.json',
  'docs/REGION_GAMEPLAY_TEST_20260714_V023.json',
  'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V023.json',
  'docs/STATIC_AUDIT_20260714_V023.json',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V023.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V023.json',
  'docs/RUNTIME_HTTP_20260714_V023.txt',
  'docs/FILE_INVENTORY_V023_SHA256.txt',
  'src/data/runtimeEffects.js',
  'src/services/EquipmentRuntimeService.js',
  'src/services/ItemRuntimeService.js',
  'src/services/FarmInventoryService.js',
  'src/services/FarmToolService.js',
  'src/services/SeasonCropService.js',
  'src/services/AnimalCareService.js',
  'src/services/LifeSimulationCoreValidationService.js',
  'src/components/UI/SceneTransitionRequestController.jsx',
  'src/components/UI/FarmToolHUD.jsx',
  'src/components/UI/AnimalCarePanel.jsx',
  'src/components/UI/FarmCommandController.jsx',
  'src/components/UI/FishingPanel.jsx',
  'scripts/run-life-simulation-core-tests.mjs',
  'scripts/export-life-simulation-core-evidence.mjs',
  'docs/LIFE_SIMULATION_CORE_VALIDATION.json',
  'docs/EQUIPMENT_ITEM_EFFECT_MATRIX.csv',
  'docs/FARM_ECONOMY_MATRIX.csv',
  'docs/RELEASE_NOTES_0.27.0.md',
  'docs/REMAINING_SCOPE_0.27.0.md',
  'docs/DESTRUCTIVE_QA_0.27.0.md',
  'docs/RUNTIME_QA_STATUS_V027.md',
  'docs/ROADMAP_ALIGNMENT_V027.md',
  'docs/BASELINE_LOCK_V027.json',
  'docs/FILE_DIFF_V026_TO_V027.txt',
  'docs/FILE_DIFF_V026_TO_V027.json',
  'docs/BUILD_20260714_V027.txt',
  'docs/LIFE_SIMULATION_CORE_TEST_20260714_V027.json',
  'docs/SIMULATION_20260714_V027.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V027.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V027.json',
  'docs/REGION_GAMEPLAY_TEST_20260714_V027.json',
  'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V027.json',
  'docs/TERRAIN_TRAVERSAL_TEST_20260714_V027.json',
  'docs/ENVIRONMENT_LIFE_TEST_20260714_V027.json',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V027.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V027.json',
  'docs/RUNTIME_HTTP_20260714_V027.txt',
  'src/data/villageResidentProfiles.js',
  'src/data/companionProfiles.js',
  'src/services/VillageRelationshipService.js',
  'src/services/VillageEconomyService.js',
  'src/services/VillageFestivalService.js',
  'src/services/CompanionRuntimeService.js',
  'src/services/VillageCompanionValidationService.js',
  'src/store/villageSlice.js',
  'src/store/companionSlice.js',
  'src/components/3D/CompanionActor.jsx',
  'src/components/Farm/CompanionHomeActors.jsx',
  'src/components/UI/StarterCompanionPanel.jsx',
  'src/components/UI/CompanionRosterPanel.jsx',
  'src/components/UI/VillageRelationsPanel.jsx',
  'src/components/UI/VillageBoardPanel.jsx',
  'scripts/generate-companion-assets.mjs',
  'scripts/run-village-companion-tests.mjs',
  'scripts/export-village-companion-evidence.mjs',
  'public/manifests/companion-production-manifest.json',
  'docs/VILLAGE_COMPANION_VALIDATION.json',
  'docs/VILLAGE_RESIDENT_MATRIX.csv',
  'docs/COMPANION_RUNTIME_MATRIX.csv',
  'docs/RELEASE_NOTES_0.28.0.md',
  'docs/REMAINING_SCOPE_0.28.0.md',
  'docs/DESTRUCTIVE_QA_0.28.0.md',
  'docs/RUNTIME_QA_STATUS_V028.md',
  'docs/ROADMAP_ALIGNMENT_V028.md',
  'docs/BASELINE_LOCK_V028.json',
  'docs/BUILD_20260714_V028.txt',
  'docs/VILLAGE_COMPANION_TEST_20260714_V028.json',
  'docs/LIFE_SIMULATION_CORE_TEST_20260714_V028.json',
  'docs/SIMULATION_20260714_V028.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V028.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V028.json',
  'docs/REGION_GAMEPLAY_TEST_20260714_V028.json',
  'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V028.json',
  'docs/TERRAIN_TRAVERSAL_TEST_20260714_V028.json',
  'docs/ENVIRONMENT_LIFE_TEST_20260714_V028.json',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V028.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V028.json',
  'docs/RUNTIME_HTTP_20260714_V028.txt',
  'docs/FILE_DIFF_V027_TO_V028.txt',
  'docs/FILE_DIFF_V027_TO_V028.json',
  'docs/FINAL_VERIFICATION_V028.json',
  'docs/FILE_INVENTORY_V028_SHA256.txt',
  'src/data/equipmentSchema.js',
  'src/services/EquipmentInstanceService.js',
  'src/services/AssetPathService.js',
  'src/services/EquipmentVisualResolverService.js',
  'src/services/AnimationStateService.js',
  'src/services/MaterialProfileService.js',
  'src/services/AssetGovernanceValidationService.js',
  'src/components/3D/EquipmentAttachmentMesh.jsx',
  'src/data/artGovernanceProfiles.js',
  'src/shaders/shaderLibrary.js',
  'scripts/art-pipeline/build-art-foundation.mjs',
  'scripts/art-pipeline/texture/pngCodec.mjs',
  'scripts/art-pipeline/texture/proceduralTextureGenerator.mjs',
  'scripts/art-pipeline/texture/svgPatternGenerator.mjs',
  'scripts/run-art-governance-tests.mjs',
  'public/textures/generated/art-foundation-manifest.json',
  'docs/ASSET_GOVERNANCE_V029.md',
  'docs/EQUIPMENT_SCHEMA_V029.md',
  'docs/ART_PIPELINE_V029.md',
  'docs/ROADMAP_800_GLB_V029_TO_V036.md',
  'docs/RELEASE_NOTES_0.29.0.md',
  'docs/DESTRUCTIVE_QA_0.29.0.md',
  'docs/ROADMAP_ALIGNMENT_V029.md',
  'docs/RUNTIME_QA_STATUS_V029.md',
  'docs/ART_FOUNDATION_GENERATION_20260714_V029.json',
  'docs/ART_GOVERNANCE_TEST_20260714_V029.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V029.json',
  'docs/SIMULATION_20260714_V029.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V029.json',
  'docs/REGION_GAMEPLAY_TEST_20260714_V029.json',
  'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V029.json',
  'docs/TERRAIN_TRAVERSAL_TEST_20260714_V029.json',
  'docs/ENVIRONMENT_LIFE_TEST_20260714_V029.json',
  'docs/LIFE_SIMULATION_CORE_TEST_20260714_V029.json',
  'docs/VILLAGE_COMPANION_TEST_20260714_V029.json',
  'docs/STATIC_AUDIT_20260714_V029.json',
  'docs/BUILD_20260714_V029.txt',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V029.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V029.json',
  'docs/BASELINE_LOCK_V029.json',
  'docs/FILE_DIFF_V028_TO_V029.txt',
  'docs/FILE_DIFF_V028_TO_V029.json',
  'docs/FINAL_VERIFICATION_V029.json',
  'docs/FILE_INVENTORY_V029_SHA256.txt',
];
const fileChecks = Object.fromEntries(requiredFiles.map((relative) => [relative, fs.existsSync(path.join(root, relative))]));
const bossSource = fs.readFileSync(path.join(root, 'src/components/Entities/Boss.jsx'), 'utf8');
const appSource = fs.readFileSync(path.join(root, 'src/App.jsx'), 'utf8');
const farmSource = fs.readFileSync(path.join(root, 'src/components/Farm/FarmScene.jsx'), 'utf8');
const regionSource = fs.readFileSync(path.join(root, 'src/components/Scenes/RegionScene.jsx'), 'utf8');
const forestSource = fs.readFileSync(path.join(root, 'src/components/Scenes/ForestRuinsScene.jsx'), 'utf8');
const storeSource = fs.readFileSync(path.join(root, 'src/store/useStore.js'), 'utf8');
const playerSource = fs.readFileSync(path.join(root, 'src/components/3D/Player.jsx'), 'utf8');
const trialControllerSource = fs.readFileSync(path.join(root, 'src/components/Entities/TrialFloorController.jsx'), 'utf8');
const regionMechanicSource = fs.readFileSync(path.join(root, 'src/components/World/RegionMechanicLayer.jsx'), 'utf8');
const runtimeTestSource = fs.readFileSync(path.join(root, 'scripts/run-production-runtime-tests.mjs'), 'utf8');
const hudLayoutSource = fs.readFileSync(path.join(root, 'src/components/UI/HUDLayoutManager.jsx'), 'utf8');
const voiceGuidanceSource = fs.readFileSync(path.join(root, 'src/components/UI/VoiceGuidanceController.jsx'), 'utf8');
const storyServiceSource = fs.readFileSync(path.join(root, 'src/services/StoryProgressService.js'), 'utf8');
const traversalServiceSource = fs.readFileSync(path.join(root, 'src/services/TraversalSurfaceService.js'), 'utf8');
const traversalLayerSource = fs.readFileSync(path.join(root, 'src/components/World/RegionTraversalLayer.jsx'), 'utf8');
const regionProductionKitSource = fs.readFileSync(path.join(root, 'src/components/World/RegionProductionKit.jsx'), 'utf8');
const monstersSource = fs.readFileSync(path.join(root, 'src/components/Entities/Monsters.jsx'), 'utf8');

const checks = {
  village: validateVillageLayout(VILLAGE_LAYOUT),
  placement: validatePlacementRules(VILLAGE_LAYOUT),
  farm: validateFarmLayout(FARM_LAYOUT),
  forest: validateForestRuinsLayout(FOREST_RUINS_LAYOUT),
  interiors: validateAllInteriors(),
  skillGraph: validateSkillGraph(),
  trialTower: validateTrialTower(),
  farmProgression: validateFarmProgression(),
  regionProduction: validateAllRegionProductionLayouts(REGION_STRUCTURE_CATALOG),
  characterPhysical: validateCharacterPhysicalProfiles(),
  productionRuntime: validateProductionRuntimeContracts(),
  regionGameplay: validateRegionGameplayProduction(),
  release022: validateRelease022Content(),
  terrainTraversal: validateTerrainTraversalFoundation(),
  environmentLife: validateEnvironmentLifeContent(),
  lifeSimulationCore: validateLifeSimulationCore(),
  villageCompanion: validateVillageCompanionContent(),
  assetGovernance: validateAssetGovernanceContracts(),
  requiredFiles: { ok: Object.values(fileChecks).every(Boolean), files: fileChecks },
  bossClickDamageRemoved: { ok: !bossSource.includes('takeHit(50)') && !bossSource.includes('or tap') },
  authoredRegionSceneRouting: {
    ok: regionSource.includes('RegionProductionTerrain') && regionSource.includes('getRegionProductionLayout') && !regionSource.includes('<RegionTerrain'),
  },
  regionGameplayRuntimeWiring: {
    ok: regionSource.includes('<RegionGameplayLayer') && appSource.includes('<DailyRiftHUD />') && storeSource.includes('recordRegionEventSignal') && storeSource.includes('completeDailyRift'),
  },
  uniqueRegionMechanicRouting: {
    ok: regionMechanicSource.includes("openPanel('regionMechanic'") && !regionMechanicSource.includes('openMathChallenge'),
  },
  pureRuntimeTestMode: {
    ok: runtimeTestSource.includes("process.argv.includes('--write-report')") && packageJson.scripts?.['runtime:production:report']?.includes('--write-report'),
  },
  globalWorldEnvironment: {
    ok: appSource.includes('<WorldEnvironment sceneId={currentScene}') &&
      !farmSource.includes('<Sky ') && !regionSource.includes('<Sky ') && !forestSource.includes('<Sky '),
  },
  characterCreation: {
    ok: storeSource.includes('completeCharacterCreation') && appSource.includes('<CharacterCreationPanel />') && appSource.includes('useGamepad()'),
  },
  childSafeDefeatFlow: {
    ok: storeSource.includes('triggerDefeat') && storeSource.includes('requestRespawn') && playerSource.includes('st.triggerDefeat?.(currentScene)') && !playerSource.includes('st.healHpPercent(100)'),
  },
  trialSceneMechanics: {
    ok: trialControllerSource.includes('<TrialRoomMechanic') && !trialControllerSource.includes('openMathChallenge'),
  },
  bossPhasedCombat: {
    ok: bossSource.includes('BossSkillTelegraph') && bossSource.includes('vulnerableUntilRef') && bossSource.includes('getBossCombatProfile') && bossSource.includes('rotationY'),
  },
  childUiLayoutSystem: {
    ok: appSource.includes('<HUDLayoutManager />') && hudLayoutSource.includes('mqDevice') && hudLayoutSource.includes('mqHandedness'),
  },
  storyRuntimeWiring: {
    ok: storeSource.includes('backfillChapterProgress') && storeSource.includes('applyStorySignal') && storyServiceSource.includes('hasExistingEvidence'),
  },
  sceneCallbackCancellation: {
    ok: storeSource.includes('sceneEpoch') && storeSource.includes('challenge.sceneEpoch === state.sceneEpoch') && storeSource.includes('sceneEpoch: state.sceneEpoch + 1'),
  },
  voiceGuidanceRuntime: {
    ok: appSource.includes('<VoiceGuidanceController />') && voiceGuidanceSource.includes('SpeechSynthesisUtterance') && voiceGuidanceSource.includes("utterance.lang = 'zh-TW'"),
  },
  segmentedTerrainRuntime: {
    ok: regionProductionKitSource.includes('<RegionTraversalLayer layout={layout}') &&
      !regionProductionKitSource.includes('<BaseTerrain layout={layout}') &&
      traversalLayerSource.includes('buildWalkableRectangles') &&
      !traversalLayerSource.includes('water-floor-collider'),
  },
  sharedTraversalProjection: {
    ok: playerSource.includes('sampleTraversalSurface') && playerSource.includes('lastSafePosition') &&
      monstersSource.includes('projectTraversalStep') && bossSource.includes('projectTraversalStep'),
  },
  routedRoadAndBridgeFoundation: {
    ok: traversalServiceSource.includes('resolveRoadPolyline') &&
      traversalServiceSource.includes('resolveBridgeGeometry') &&
      traversalServiceSource.includes('validateTraversalLayout'),
  },
  lifeCoreRuntimeWiring: {
    ok: appSource.includes('<SceneTransitionRequestController />') &&
      appSource.includes('<FarmCommandController />') &&
      appSource.includes('<FarmToolHUD />') &&
      storeSource.includes('resolveItemUse') &&
      storeSource.includes('resolveEquipmentRuntime') &&
      storeSource.includes('farmProducts') &&
      farmSource.includes('prepareCell'),
  },
  villageCompanionRuntimeWiring: {
    ok: appSource.includes('<StarterCompanionPanel />') &&
      appSource.includes('<FairyCompanion />') &&
      storeSource.includes('createVillageSlice') &&
      storeSource.includes('createCompanionSlice') &&
      !storeSource.includes("if (!equipped.pet) equipped.pet = 'pet_01'") &&
      packageJson.scripts?.['village:companion:test']?.includes('run-village-companion-tests.mjs'),
  },
  v028EvidenceChain: {
    ok: [
      'public/manifests/companion-production-manifest.json',
      'docs/VILLAGE_COMPANION_VALIDATION.json',
      'docs/VILLAGE_RESIDENT_MATRIX.csv',
      'docs/COMPANION_RUNTIME_MATRIX.csv',
      'docs/RELEASE_NOTES_0.28.0.md',
      'docs/REMAINING_SCOPE_0.28.0.md',
      'docs/DESTRUCTIVE_QA_0.28.0.md',
      'docs/RUNTIME_QA_STATUS_V028.md',
      'docs/ROADMAP_ALIGNMENT_V028.md',
      'docs/BASELINE_LOCK_V028.json',
      'docs/BUILD_20260714_V028.txt',
      'docs/VILLAGE_COMPANION_TEST_20260714_V028.json',
      'docs/LIFE_SIMULATION_CORE_TEST_20260714_V028.json',
      'docs/SIMULATION_20260714_V028.json',
      'docs/REGION_PRODUCTION_TEST_20260714_V028.json',
      'docs/PRODUCTION_RUNTIME_TEST_20260714_V028.json',
      'docs/REGION_GAMEPLAY_TEST_20260714_V028.json',
      'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V028.json',
      'docs/TERRAIN_TRAVERSAL_TEST_20260714_V028.json',
      'docs/ENVIRONMENT_LIFE_TEST_20260714_V028.json',
      'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V028.json',
      'docs/DEPENDENCY_AUDIT_FULL_20260714_V028.json',
      'docs/RUNTIME_HTTP_20260714_V028.txt',
      'docs/FILE_DIFF_V027_TO_V028.txt',
      'docs/FILE_DIFF_V027_TO_V028.json',
      'docs/FINAL_VERIFICATION_V028.json',
      'docs/FILE_INVENTORY_V028_SHA256.txt',
  'docs/BUILD_20260714_V028.txt',
  'docs/VILLAGE_COMPANION_TEST_20260714_V028.json',
  'docs/LIFE_SIMULATION_CORE_TEST_20260714_V028.json',
  'docs/SIMULATION_20260714_V028.json',
  'docs/REGION_PRODUCTION_TEST_20260714_V028.json',
  'docs/PRODUCTION_RUNTIME_TEST_20260714_V028.json',
  'docs/REGION_GAMEPLAY_TEST_20260714_V028.json',
  'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V028.json',
  'docs/TERRAIN_TRAVERSAL_TEST_20260714_V028.json',
  'docs/ENVIRONMENT_LIFE_TEST_20260714_V028.json',
  'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V028.json',
  'docs/DEPENDENCY_AUDIT_FULL_20260714_V028.json',
  'docs/RUNTIME_HTTP_20260714_V028.txt',
  'docs/FILE_DIFF_V027_TO_V028.txt',
  'docs/FILE_DIFF_V027_TO_V028.json',
  'docs/FINAL_VERIFICATION_V028.json',
  'docs/FILE_INVENTORY_V028_SHA256.txt',
      'scripts/run-village-companion-tests.mjs',
      'scripts/export-village-companion-evidence.mjs',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
  v029FoundationChain: {
    ok: [
      'src/data/equipmentSchema.js',
      'src/services/EquipmentInstanceService.js',
      'src/services/AssetPathService.js',
      'src/services/AssetGovernanceValidationService.js',
      'src/data/artGovernanceProfiles.js',
      'src/shaders/shaderLibrary.js',
      'scripts/art-pipeline/build-art-foundation.mjs',
      'scripts/run-art-governance-tests.mjs',
      'public/textures/generated/art-foundation-manifest.json',
      'docs/ASSET_GOVERNANCE_V029.md',
      'docs/EQUIPMENT_SCHEMA_V029.md',
      'docs/ART_PIPELINE_V029.md',
      'docs/ROADMAP_800_GLB_V029_TO_V036.md',
      'docs/RELEASE_NOTES_0.29.0.md',
      'docs/DESTRUCTIVE_QA_0.29.0.md',
      'docs/ROADMAP_ALIGNMENT_V029.md',
      'docs/RUNTIME_QA_STATUS_V029.md',
      'docs/ART_FOUNDATION_GENERATION_20260714_V029.json',
      'docs/ART_GOVERNANCE_TEST_20260714_V029.json',
      'docs/PRODUCTION_RUNTIME_TEST_20260714_V029.json',
      'docs/SIMULATION_20260714_V029.json',
      'docs/REGION_PRODUCTION_TEST_20260714_V029.json',
      'docs/REGION_GAMEPLAY_TEST_20260714_V029.json',
      'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V029.json',
      'docs/TERRAIN_TRAVERSAL_TEST_20260714_V029.json',
      'docs/ENVIRONMENT_LIFE_TEST_20260714_V029.json',
      'docs/LIFE_SIMULATION_CORE_TEST_20260714_V029.json',
      'docs/VILLAGE_COMPANION_TEST_20260714_V029.json',
      'docs/BUILD_20260714_V029.txt',
      'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V029.json',
      'docs/DEPENDENCY_AUDIT_FULL_20260714_V029.json',
      'docs/BASELINE_LOCK_V029.json',
      'docs/FILE_DIFF_V028_TO_V029.txt',
      'docs/FILE_DIFF_V028_TO_V029.json',
      'docs/FINAL_VERIFICATION_V029.json',
      'docs/FILE_INVENTORY_V029_SHA256.txt',
    ].every((relative) => fs.existsSync(path.join(root, relative))) &&
      packageJson.scripts?.['art:foundation:generate']?.includes('build-art-foundation.mjs') &&
      packageJson.scripts?.['art:governance:test']?.includes('run-art-governance-tests.mjs'),
  },
  packageLockSync: {
    ok: packageJson.version === packageLock.version && packageJson.version === packageLock.packages?.['']?.version,
  },
  v027EvidenceChain: {
    ok: [
      'docs/LIFE_SIMULATION_CORE_VALIDATION.json',
      'docs/EQUIPMENT_ITEM_EFFECT_MATRIX.csv',
      'docs/FARM_ECONOMY_MATRIX.csv',
      'docs/RELEASE_NOTES_0.27.0.md',
      'docs/REMAINING_SCOPE_0.27.0.md',
      'docs/DESTRUCTIVE_QA_0.27.0.md',
      'docs/RUNTIME_QA_STATUS_V027.md',
      'docs/ROADMAP_ALIGNMENT_V027.md',
      'docs/BASELINE_LOCK_V027.json',
      'scripts/run-life-simulation-core-tests.mjs',
      'scripts/export-life-simulation-core-evidence.mjs',
      'docs/FILE_DIFF_V026_TO_V027.txt',
      'docs/FILE_DIFF_V026_TO_V027.json',
      'docs/BUILD_20260714_V027.txt',
      'docs/LIFE_SIMULATION_CORE_TEST_20260714_V027.json',
      'docs/SIMULATION_20260714_V027.json',
      'docs/REGION_PRODUCTION_TEST_20260714_V027.json',
      'docs/PRODUCTION_RUNTIME_TEST_20260714_V027.json',
      'docs/REGION_GAMEPLAY_TEST_20260714_V027.json',
      'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V027.json',
      'docs/TERRAIN_TRAVERSAL_TEST_20260714_V027.json',
      'docs/ENVIRONMENT_LIFE_TEST_20260714_V027.json',
      'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V027.json',
      'docs/DEPENDENCY_AUDIT_FULL_20260714_V027.json',
      'docs/RUNTIME_HTTP_20260714_V027.txt',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
  v026EvidenceChain: {
    ok: [
      'docs/ENVIRONMENT_LIFE_MATRIX.md',
      'docs/FINAL_VERIFICATION_SUMMARY.json',
      'docs/PRODUCTION_RELEASE.md',
      'docs/REMAINING_SCOPE_CURRENT.md',
      'docs/FILE_DIFF_V023_TO_V026.txt',
      'docs/FILE_DIFF_V023_TO_V026.json',
      'docs/FILE_INVENTORY_SHA256.txt',
      'scripts/run-environment-life-tests.mjs',
      'scripts/generate-region-environment-assets.mjs',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
  v023EvidenceChain: {
    ok: [
      'public/manifests/terrain-traversal-manifest.json',
      'docs/TERRAIN_TRAVERSAL_VALIDATION.json',
      'docs/TERRAIN_TRAVERSAL_MATRIX.csv',
      'docs/RELEASE_NOTES_0.23.0.md',
      'docs/REMAINING_SCOPE_0.23.0.md',
      'docs/DESTRUCTIVE_QA_0.23.0.md',
      'docs/RUNTIME_QA_STATUS_V023.md',
      'docs/BASELINE_LOCK_V023.json',
      'docs/FILE_DIFF_V022_TO_V023.txt',
      'docs/FILE_DIFF_V022_TO_V023.json',
      'docs/BUILD_20260714_V023.txt',
      'docs/TERRAIN_TRAVERSAL_TEST_20260714_V023.json',
      'docs/SIMULATION_20260714_V023.json',
      'docs/REGION_PRODUCTION_TEST_20260714_V023.json',
      'docs/PRODUCTION_RUNTIME_TEST_20260714_V023.json',
      'docs/REGION_GAMEPLAY_TEST_20260714_V023.json',
      'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V023.json',
      'docs/STATIC_AUDIT_20260714_V023.json',
      'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V023.json',
      'docs/DEPENDENCY_AUDIT_FULL_20260714_V023.json',
      'docs/RUNTIME_HTTP_20260714_V023.txt',
      'docs/FILE_INVENTORY_V023_SHA256.txt',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
  v022EvidenceChain: {
    ok: [
      'public/manifests/release-content-manifest.json',
      'docs/RELEASE_022_VALIDATION.json',
      'docs/COMBAT_BOSS_ELITE_MATRIX.csv',
      'docs/TRIAL_TOWER_100_FLOOR_MATRIX.csv',
      'docs/STORY_QUEST_MATRIX.csv',
      'docs/UI_ACCESSIBILITY_MATRIX.csv',
      'docs/RELEASE_NOTES_0.22.0.md',
      'docs/REMAINING_SCOPE_0.22.0.md',
      'docs/DESTRUCTIVE_QA_0.22.0.md',
      'docs/RUNTIME_QA_STATUS_V022.md',
      'docs/BASELINE_LOCK_V022.json',
      'docs/FILE_DIFF_V019_TO_V022.txt',
      'docs/FILE_DIFF_V019_TO_V022.json',
      'docs/BUILD_20260714_V022.txt',
      'docs/SIMULATION_20260714_V022.json',
      'docs/REGION_PRODUCTION_TEST_20260714_V022.json',
      'docs/PRODUCTION_RUNTIME_TEST_20260714_V022.json',
      'docs/REGION_GAMEPLAY_TEST_20260714_V022.json',
      'docs/RELEASE_DESTRUCTIVE_TEST_20260714_V022.json',
      'docs/STATIC_AUDIT_20260714_V022.json',
      'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V022.json',
      'docs/DEPENDENCY_AUDIT_FULL_20260714_V022.json',
      'docs/RUNTIME_HTTP_20260714_V022.txt',
      'docs/FILE_INVENTORY_V022_SHA256.txt',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
  v019EvidenceChain: {
    ok: [
      'public/manifests/region-gameplay-manifest.json',
      'docs/REGION_GAMEPLAY_VALIDATION.json',
      'docs/REGION_GAMEPLAY_MATRIX.csv',
      'docs/RELEASE_NOTES_0.19.0.md',
      'docs/REMAINING_SCOPE_0.19.0.md',
      'docs/BASELINE_LOCK_V019.json',
      'docs/FILE_DIFF_V018_TO_V019.txt',
      'docs/FILE_DIFF_V018_TO_V019.json',
      'docs/BUILD_20260714_V019.txt',
      'docs/SIMULATION_20260714_V019.json',
      'docs/REGION_PRODUCTION_TEST_20260714_V019.json',
      'docs/PRODUCTION_RUNTIME_TEST_20260714_V019.json',
      'docs/DEPENDENCY_AUDIT_PRODUCTION_20260714_V019.json',
      'docs/DEPENDENCY_AUDIT_FULL_20260714_V019.json',
      'docs/RUNTIME_HTTP_20260714_V019.txt',
      'docs/RUNTIME_QA_STATUS_V019.md',
      'docs/FILE_INVENTORY_V019_SHA256.txt',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
  evidenceChain: {
    ok: [
      'docs/FILE_DIFF_20260714_V017.txt',
      'docs/FILE_DIFF_20260714_V017.json',
      'docs/BUILD_20260714_V017.txt',
      'docs/SIMULATION_20260714_V017.txt',
      'docs/REGION_PRODUCTION_TEST_20260714_V017.json',
      'docs/DEPENDENCY_AUDIT_20260714_V017.json',
      'docs/RUNTIME_HTTP_20260714_V017.txt',
      'docs/RUNTIME_20260714_V017.md',
      'docs/CHANGESET_20260714_V017_REGION_CHARACTER_PRODUCTION.md',
      'docs/REMAINING_SCOPE_20260714_V017.md',
      'docs/BASELINE_LOCK_V017.json',
      'docs/REGION_PRODUCTION_MATRIX.csv',
      'docs/CHARACTER_PHYSICAL_MATRIX.csv',
      'docs/WORK_LEDGER.csv',
    ].every((relative) => fs.existsSync(path.join(root, relative))),
  },
};
const failures = Object.entries(checks).filter(([, value]) => value.ok === false);
const warnings = Object.entries(checks).flatMap(([name, value]) => (value.warnings || []).map((warning) => `${name}: ${warning}`));
const report = {
  generatedAt: new Date().toISOString(),
  version: `${packageJson.version}-art-governance-foundation`,
  ok: failures.length === 0 && warnings.length === 0,
  failureCount: failures.length,
  warningCount: warnings.length,
  failures: failures.map(([name, value]) => ({ name, value })),
  warnings,
  checks,
};
console.log(JSON.stringify(report, null, 2));
if (!report.ok) process.exitCode = 1;
