// 真實載入畫面：進度來自 Manifest、字型、WebGL、Physics、場景配置與第一幀。
import { useEffect, useMemo, useRef, useState } from 'react';
import { beginRealLoad,getLoadSnapshot,resetLoadProgress,subscribeLoad } from '../../input/loadProgress.js';
const LESSONS=[
 {icon:'🌟',title:'廣場石板',question:'廣場有 4 排石板，每排 6 塊，一共有幾塊？',answer:'4 × 6 = 24'},
 {icon:'🌾',title:'農場準備',question:'3 塊田地各需要 5 包種子，共需要幾包？',answer:'3 × 5 = 15'},
 {icon:'🛍️',title:'商店找零',question:'藥水售價 35G，付 50G，應找回多少？',answer:'50 − 35 = 15G'},
 {icon:'🌉',title:'橋梁測量',question:'橋長 8 公尺，走了一半，還剩多少？',answer:'8 ÷ 2 = 4 公尺'},
];
export default function LoadingScreen(){const[snapshot,setSnapshot]=useState(getLoadSnapshot),[visible,setVisible]=useState(true),[show,setShow]=useState(false),done=useRef(false),lesson=useMemo(()=>LESSONS[Math.floor(Math.random()*LESSONS.length)],[]);useEffect(()=>{beginRealLoad();const unsub=subscribeLoad(next=>{setSnapshot(next);if(next.ready&&!done.current){done.current=true;window.setTimeout(()=>setVisible(false),450)}});setSnapshot(getLoadSnapshot());return unsub},[]);if(!visible)return null;const retry=()=>{done.current=false;setShow(false);resetLoadProgress();beginRealLoad()};return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-gradient-to-b from-[#83d7ff] via-[#d9f5ff] to-[#8fd477] px-5 text-slate-800"><div className="w-full max-w-3xl rounded-[32px] border-4 border-white/75 bg-white/88 p-6 shadow-2xl backdrop-blur-md md:p-9"><div className="grid gap-6 md:grid-cols-[1.05fr_.95fr] md:items-center"><section><div className="text-xs font-black tracking-[.28em] text-emerald-700">MATHQUEST 3D</div><h1 className="mt-2 text-3xl font-black md:text-5xl">正在建造星光村</h1><p className="mt-3 text-sm font-semibold text-slate-500">{snapshot.stage.label}</p><div className="mt-5 h-5 overflow-hidden rounded-full border-2 border-white bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-emerald-400 via-yellow-300 to-sky-400 transition-[width] duration-300" style={{width:`${snapshot.progress}%`}}/></div><div className="mt-2 flex justify-between text-xs font-bold text-slate-500"><span>{snapshot.progress}%</span><span>{snapshot.ready?'可以開始冒險':'正在準備實際場景物件'}</span></div>{snapshot.error&&<div className="mt-5 rounded-2xl border-2 border-red-300 bg-red-50 p-4"><div className="font-black text-red-700">載入失敗</div><div className="mt-1 text-xs text-red-600">{snapshot.error}</div><button onClick={retry} className="mt-3 rounded-xl bg-red-600 px-4 py-2 text-sm font-black text-white">重新載入</button></div>}</section><section className="rounded-[26px] border-2 border-amber-200 bg-[#fff9df] p-5 shadow-lg"><div className="text-5xl">{lesson.icon}</div><div className="mt-2 text-xs font-black tracking-wider text-amber-700">載入中的數學小知識</div><h2 className="mt-1 text-xl font-black">{lesson.title}</h2><p className="mt-3 text-sm font-semibold leading-6 text-slate-600">{lesson.question}</p><button onClick={()=>setShow(v=>!v)} className="mt-4 rounded-xl bg-amber-400 px-4 py-2 text-sm font-black text-amber-950">{show?'隱藏解法':'看看解法'}</button>{show&&<div className="mt-3 rounded-xl bg-white px-4 py-3 text-center text-lg font-black text-emerald-700">{lesson.answer}</div>}</section></div></div></div>}
